### ISSUE TITLE
Lets make a major change

### ISSUE THREAD

**Issue by cdupuis** [atomisthqa/handlers#141] opened 2017-01-20 19:49 UTC

**Comment by cdupuis** [comment] 2017-01-20 19:50
Oh. Friday is best for that.

**Comment by slimslenderslacks** [comment] 2017-01-20 19:51
Okay, it's assigned to me and I think I know what the problem is.

**Comment by jessitron** [comment] 2017-01-31 01:10
no way

**Comment by jessitron** [comment] 2017-01-31 01:20
how about now

**Comment by cdupuis** [comment] 2017-01-31 01:38
This is my awesome event

**Comment by jessitron** [comment] 2017-01-31 02:41
is the formatting better? Try making your own comment here please

**Closed** 2017-02-03 17:40 UTC
Labels: bug, help wanted
